"""
Test-suite runner.

Takes a `GeneratedTestSuite` and runs it against a candidate server,
returning a structured `VerificationRun` summarizing what passed, what
failed, and which security properties were violated.

We run pytest in a subprocess (not in-process) because the test code is
generated by an LLM and may have arbitrary imports or syntax issues —
keeping it out of our process keeps the system robust to bad gens.

Sandboxing
----------
This prototype runs tests against an HTTP endpoint the user provides
(typically `http://localhost:<port>` after `python server.py` was
started). It does NOT itself spawn the server. The next iteration
should add a fixture-launcher that:
    1. Spawns the candidate server in a constrained namespace
       (firejail / bubblewrap / a container) with no real outbound
       network and a tmpfs data dir,
    2. Waits for /health,
    3. Runs the tests against that sandboxed instance.
This is left as a TODO because the fellowship's first goal is to make
the spec → tests → results loop work end-to-end; hardened sandboxing
is independently engineerable later.
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from .adversarial import GeneratedTestSuite


@dataclass
class TestResult:
    nodeid: str
    outcome: str           # "passed", "failed", "error", "skipped"
    duration_s: float
    target_property: str | None = None  # from @pytest.mark.target("...")
    failure_excerpt: str | None = None


@dataclass
class VerificationRun:
    suite: GeneratedTestSuite
    server_url: str
    results: list[TestResult] = field(default_factory=list)
    summary: dict[str, int] = field(default_factory=dict)
    # Properties for which at least one targeted test failed
    violated_properties: list[str] = field(default_factory=list)

    @property
    def passed(self) -> bool:
        return not self.violated_properties and self.summary.get("failed", 0) == 0


def run_test_suite(
    suite: GeneratedTestSuite,
    server_url: str,
    pytest_args: list[str] | None = None,
    fixture_file: str | Path | None = None,
) -> VerificationRun:
    """Run the suite. Returns a VerificationRun.

    `fixture_file` (if given) is a Python file defining the pytest
    fixtures the generator assumed (`client`, plus anything in
    `spec.fixtures`). For the demo, see `examples/server_demo/conftest.py`.
    """
    if shutil.which("pytest") is None:
        raise RuntimeError("pytest is not installed; pip install pytest requests")

    with tempfile.TemporaryDirectory(prefix="safe_scaffold_") as td:
        td_path = Path(td)
        (td_path / "test_generated.py").write_text(suite.pytest_code)
        if fixture_file is not None:
            shutil.copy(fixture_file, td_path / "conftest.py")
        else:
            (td_path / "conftest.py").write_text(_DEFAULT_CONFTEST)

        report_path = td_path / "report.json"
        cmd = [
            "pytest", "-q", "--no-header",
            f"--json-report", f"--json-report-file={report_path}",
            *(pytest_args or []),
            str(td_path / "test_generated.py"),
        ]
        env = {"SAFE_SCAFFOLD_SERVER_URL": server_url}
        try:
            subprocess.run(cmd, cwd=td, env={**__import__("os").environ, **env}, check=False)
        except FileNotFoundError as e:
            raise RuntimeError(
                "pytest-json-report plugin not installed; "
                "pip install pytest-json-report"
            ) from e

        run = VerificationRun(suite=suite, server_url=server_url)
        if not report_path.exists():
            return run

        data = json.loads(report_path.read_text())
        for t in data.get("tests", []):
            target = _extract_target_marker(t)
            run.results.append(TestResult(
                nodeid=t["nodeid"],
                outcome=t["outcome"],
                duration_s=t.get("duration", 0.0),
                target_property=target,
                failure_excerpt=(
                    t.get("call", {}).get("longrepr") if t["outcome"] != "passed"
                    else None
                ),
            ))
        run.summary = data.get("summary", {})
        run.violated_properties = sorted({
            r.target_property for r in run.results
            if r.outcome == "failed" and r.target_property
        })
        return run


_TARGET_MARK_RE = re.compile(r"target\(['\"]([^'\"]+)['\"]\)")


def _extract_target_marker(t: dict) -> str | None:
    """Pull the property name out of a `@pytest.mark.target("foo")` mark.

    pytest-json-report includes markers under 'markers' on each test.
    Older versions place them in metadata; we try both.
    """
    markers = t.get("markers") or t.get("keywords") or []
    if isinstance(markers, dict):
        markers = list(markers.keys())
    for m in markers:
        if isinstance(m, str):
            mm = _TARGET_MARK_RE.search(m)
            if mm:
                return mm.group(1)
            # fallback: "target[foo]" style
            if m.startswith("target[") and m.endswith("]"):
                return m[len("target["):-1]
    return None


_DEFAULT_CONFTEST = '''\
"""Minimal conftest for safe-scaffold-generated suites.

Provides a `client` fixture that talks to the URL given in
SAFE_SCAFFOLD_SERVER_URL. Override or extend in your own conftest if
your server needs auth bootstrapping (e.g. seeded users, tokens).
"""
import os
import pytest
import requests


class _Client:
    def __init__(self, base):
        self.base = base.rstrip("/")
        self.session = requests.Session()

    def _abs(self, path):
        return self.base + path if path.startswith("/") else path

    def get(self, path, **kw):    return self.session.get(self._abs(path), **kw)
    def post(self, path, **kw):   return self.session.post(self._abs(path), **kw)
    def put(self, path, **kw):    return self.session.put(self._abs(path), **kw)
    def patch(self, path, **kw):  return self.session.patch(self._abs(path), **kw)
    def delete(self, path, **kw): return self.session.delete(self._abs(path), **kw)


@pytest.fixture
def client():
    return _Client(os.environ["SAFE_SCAFFOLD_SERVER_URL"])


def pytest_configure(config):
    config.addinivalue_line("markers", "target(name): security property under test")
'''
